### ISSUE TITLE
Can t open the launcher

### ISSUE THREAD

**Issue by brutalzinn** [dedepete/FreeLauncher#57] opened 2018-10-20 01:13 UTC
Hello, well ... apparently the message appears: "It seems like it's your first time opening the launcher and you do not have an Internet connection or can not download server versions." something similar with this message. "can you help me with this bug? I can not open the launcher

**Comment by dedepete** [comment] 2018-10-20 16:39
Duplicate of #56.

**Closed by dedepete** 2018-10-20 16:39 UTC
Labels: duplicate
